services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      retries: 20
  app:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    container_name: app-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint:
      [
        "sh",
        "-c",
        "until wget -q --spider --user ${RABBITMQ_USER} --password ${RABBITMQ_PASSWORD} http://rabbitmq:${RABBITMQ_MANAGEMENT_PORT}/api/aliveness-test/%2F; do echo 'Waiting for RabbitMQ...'; sleep 2; done; echo 'RabbitMQ is ready!'; ./main",
      ]
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    restart: unless-stopped
    ports:
      - ${SWAGGER_PORT}:8080
    volumes:
      - ../api/docs/swagger.json:/spec/docs/swagger.json
    environment:
      SWAGGER_JSON: /spec/docs/swagger.json

  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - "9001:9001"

volumes:
  rabbitmq-data:
