services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: app-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../internal/sql/:/docker-entrypoint-initdb.d/

  app:
    build:
      context: ../
      dockerfile: deployments/dockerfile
    container_name: app
    restart: unless-stopped
    command: go run main.go
    ports:
      - "80:80"
    volumes:
      - ./:/app

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /oas/openapi.yml
    ports:
      - "8080:8080"
    volumes:
      - ../api:/oas

volumes:
  db-data:
  rabbitmq-data:
