services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_USE_LONGNAME: no
      RABBITMQ_MAX_MESSAGES: 1000
      RABBITMQ_MAX_MESSAGES_PER_CONNECTION: 100
      RABBITMQ_DISK_ALERT_THRESHOLD: 10%
      RABBITMQ_DISK_CHECKERS_THRESHOLD: 5%
      RABBITMQ_DISK_ERROR_THRESHOLD: 5%
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

  app:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    container_name: app-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint:
      - "./main"

volumes:
  rabbitmq-data:
