services:

  db:
    image: postgres
    restart:  unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  app:
    build: 
          context: ../
          dockerfile: deployments/dockerfile
    restart: unless-stopped
    command: go run main.go
    ports:
      - "8080:80"